### ISSUE TITLE
Segmentation fault in 'error' module for Fe-54 ENDF file

### ISSUE THREAD

**Issue by jlconlin** [njoy/NJOY2016#152]
I’m trying to process multigroup covariance matrices of Fe-54. When I’m reading the ENDF file from ENDF8.0, NJOY21 crashes with a simple segmentation fault. I haven’t been able to reproduce the segmentation fault with ENDF7.1 or JEFF3.3 ENDF files with the same NJOY input.

I've included the NJOY [input deck](https://github.com/njoy/NJOY2016/files/4315157/input.txt) and the [tape20](https://github.com/njoy/NJOY2016/files/4315158/tape20.txt)

**Comment by jlconlin** [comment]
Unfortunately, this errors in different modules depending on whether you have compiled in debug mode or in release mode. You can see from captured output below that NJOY fails in ERRORR in release mode, but in GROUPR in debug mode.

**release mode**
```
<Lots of stuff here>
 ---message from lunion---xsec nonzero at threshold for mt=633
                          adjusted using jump in xsec

 broadr...                                                                1.5s

 groupr...                                                                2.4s

 moder...                                                                 3.4s

 errorr...                                                                7.5s
At line 56 of file /Users/jlconlin/NJOY21/Code/NJOY2016/src/endf.f90 (unit = 91, file = 'tape91')
Fortran runtime error: Bad value during floating point read
```

**debug mode**
```
 ---message from lunion---xsec nonzero at threshold for mt=633
                          adjusted using jump in xsec

 broadr...                                                               11.0s

 groupr...                                                               14.2s

Program received signal SIGFPE: Floating-point exception - erroneous arithmetic operation.
```

**Comment by nathangibson14** [comment]
There are many issues at play in this one, some of which have been identified/solved, so I am going to close it.

Issues here:

- Fe-54 has an incomplete definition for lumped covariances, an evaluation problem which causes NJOY to crash.
- Fe-54 uses LRF7 for MF2 and does not include MF32.  This causes NJOY to crash and is bug to be fixed imminently.
- Fe-54 crashes in GROUPR when in debug mode but not in release mode.  This is unrelated to ERRORR but should be addressed.  I'll open a new issue for it.
- The input file given as an example here has a typo in ERRORR, using 91 instead of -91.
