### ISSUE TITLE
Problems processing MF34 for ENDF/B-VIII.0 in 235U and 238U

### ISSUE THREAD

**Issue by ocabellos** [njoy/NJOY2016#203]
Dear NJOY Team,

I have processed MF34 for 235U and 238U in ENDF/B-VIII.0 using NJOY2016.63.
Unfortunately, NJOY2016.63 failed in ERRORR module. 

Firstly, NJOY stops saying: "***error in covcal***storage exceeded in loc."

I have increased "locm" value in subroutine "covcal".

Then, NJOY failed again saying:"***error in covcal***mfcov mt found not equal to input mt."
 
Any idea?? Thanks in advance for your time.

My best regards,
Oscar Cabellos (UPM, Spain)

PD: I attach my two inputs. MF34.txt reads tape21 and tape 31 processed with MF33.txt
[MF34.txt](https://github.com/njoy/NJOY2016/files/6579785/MF34.txt)
[MF33.txt](https://github.com/njoy/NJOY2016/files/6579786/MF33.txt)

**Comment by ocabellos** [comment]
This issue is already in #122...
"ERRORR processing issue for MF34 with multiple subsections"

**Comment by whaeck** [comment]
ENDF/B-VIII.0 U235 and U238 MF34 have been on my todo list for a long time. Now seems as good a time as any to actually look into it.

The issue of not finding the proper MT number, might indicate a problem in ERRORR while reading the ENDF file (there might be an unimplemented format choice that causes ERRORR to not properly read the entire MF38 MT2 section).

**Comment by whaeck** [comment]
@ocabellos I've diagnosed the problem and provided a fix in fix/endf80-mf34 but the resulting covariance matrix is incorrect because only the first of the NI subsubsection is being used in the output (see issue #122 for a more detailed explanation). The matrices associated to each of the subsubsections are calculated and stored in a temporary file though, so we'll still need to fix the covcal routine. Unfortunately, I don't have the time to deal with that right now. I'll open an issue to track that problem separately.

I'm closing this issue and the other one now that the fix is up for merging, and with the new issue to track the covout subroutine issue.
