### ISSUE TITLE
Possible wrong value for qdel

### ISSUE THREAD

**Issue by tegaines** [njoy/NJOY2016#209]
In heatr for tabulated mt458, if no table for END is provided the qdel value is increased by c458(5) on line 734, which for ENDF/B-VIII U235, this value is 8074. However if the END table is provided, qdel is increased by scr(7) which happens to be the number of XY pairs in the upcoming table which ends up being the value of 5; this seems either wrong or a strange value to choose?

The same is done for the EGD and EB table. Is this right?

https://github.com/njoy/NJOY2016/blob/6ef2a1d04ba3cad3c114abaaf6069e317364158d/src/heatr.f90#L721

**Comment by whaeck** [comment]
At first glance, you appear to be onto something and you're probably right. I had a quick look at the code and I have to admit I don't understand how I could have made such a mistake. I blame the reviewer who did not see it either :-)

I'll continue to look into this and will keep you informed.

**Comment by whaeck** [comment]
I had forgotten about this but I have now looked into it and can say that the coding might indeed be incorrect.

qdel represents the delayed fission Q at 0 eV (used for the thermal point representation of this component of the Q value). In the loop on line 693-733, we loop over all tabulated components that are present and read in the various TAB1 records into the scr array. We then store the data in the appropriate arrays. For qdel, when the data is tabulated, I would need the first Q value of the table, which is actually stored in scr(6+2*n1h+2) instead of scr(7). scr(7) actually points to the the NBT,INT data of the TAB1.
