### ISSUE TITLE
 ***error in unrest***bad value for nres or emin>emax, increase dmin

### ISSUE THREAD

**Issue by nicoloabrate** [njoy/NJOY2016#225]
Dear developers,
I am not able to understand how to fix this issue. This error is reported on the manual but I do not find "dmin" on the manual. What is it?

The same input with the same ENDF tape works fine with njoy-2016.47.
The tape was produced running the T6 code. My objective is to generate an ACE file for MCNP/Serpent calculations.

The log is 
`
 njoy 2016.55  21Jan20                                       11/07/21 09:51:36
 *****************************************************************************

 moder...                                                                 0.0s

 reconr...                                                                0.2s

 broadr...                                                                5.7s

 unresr...                                                               12.1s

 heatr...                                                                12.4s

 ---message from hinit---mt19 has no spectrum
                          mt18 spectrum will be used.

 ---message from hinit---mf6, mt102 does not give recoil za= 90233
                          photon momentum recoil used.

 ---message from nheat---changed q from   1.884700E+08 to   1.719080E+08
                          for mt  18 by taking out delayed components

 heatr...                                                                19.2s

 ---message from hinit---mt19 has no spectrum
                          mt18 spectrum will be used.

 ---message from hinit---mf6, mt102 does not give recoil za= 90233
                          photon momentum recoil used.

 ---message from nheat---changed q from   1.884700E+08 to   1.719080E+08
                          for mt  18 by taking out delayed components

 gaspr...                                                                25.6s

 moder...                                                                28.1s

 purr...                                                                 32.3s

 mat = 9040                                                              32.3s

 ***error in unrest***bad value for nres or emin>emax, increase dmin

Note: The following floating-point exceptions are signalling: IEEE_DIVIDE_BY_ZERO IEEE_DENORMAL
STOP 77
`
while the tape and the input are attached (I had to add a txt extension to upload them here)

Thank you so much,
Nico
[njoyinp.txt](https://github.com/njoy/NJOY2016/files/7491984/njoyinp.txt)
[tape20.txt](https://github.com/njoy/NJOY2016/files/7491985/tape20.txt)

**Comment by nicoloabrate** [comment]
I am sorry, I forgot to add further important details: the raw ENDF file I attached (tape20) was generated with the T6 package. I noticed that ACE files were generated so I thought that the NJOY version inside of if (2016.47) was fine, but it is not: the same error occurs. 
The ACE files are generated using PREPRO, which is included as well in the T6 package, but apparently no unresolved resonance probability tables are included in these files. I am wondering if the problem is related to NJOY or to the ENDF file itself...

**Comment by whaeck** [comment]
The error message you are getting was added quite some ago to address issues in the generation of the probability tables for when ENDF/B-VIII.0 came out. When calculating a probability table, we need to generate resonance data in a large enough energy region. To determine that energy region, we use the smallest value of the average level spacing found in the evaluation. For certain evaluations where the level spacing is very large (of the order of keV or larger) older NJOY versions would calculate tables that were generated over a too small energy region. These tables sometimes had zero probability bins or even bins with 99% probability. At the time, the issue was traced back to the initialisation of dmin. The message is there to inform us that the value of dmin is not high enough and that it needs to be changed. To be honest, I did not expect this message to ever pop up. You can find more information here: #59

The problem here is actually not related to the value of dmin. In the case of this Th232 evaluation, the unresolved resonance region at the end of MF2 MT151 consists of only 2 lines and there are no unresolved resonance parameters given (NLS = 0). It looks as if the file is incomplete. While the file is technically "legal", it would be better to just remove the unresolved resonance region in the file altogether since there is no data in it to begin with.

We could add a test to verify the value of NLS before doing work and simply skip the empty unresolved data section but I'm not in favour of that. In my opinion, this is an evaluation issue that must be addressed in the ENDF file directly and not by the processing code. If ACEMAker was used to generate the ACE file, the tool probably has silently ignored the empty unresolved resonance region.

I'm tagging @jchsublet on this issue to make sure the TENDL folks are aware of this.

**Comment by jchsublet** [comment]
@whaeck understood and agreed the solution needs to comes from the evaluation !
@nicoloabrate pending a TENDL-2021 modification, I suggest you remove the Purr input as there is no URR

**Comment by jchsublet** [comment]
With hindsight it seems that the T6 package and/or its input used to produce this non official TENDL-2021 evaluation is the main reason behind the rogue two URR lines. The official pre-TENDL-2021 n-Th232 evaluation available on the PSI web site is properly formatted by TARES and allow the above NJOY input deck to terminates properly

@whaeck issue solved outside NJOY remit
