### ISSUE TITLE
'Negative' gamma energy in MF6 upsetting heatr JENDL5

### ISSUE THREAD

**Issue by tegaines** [njoy/NJOY2016#257]
Multiple nuclides in JENDL-5.0 for MT102 provide gamma distributions with primary gammas represented as negatives. Heatr uses these gammas as negatives resulting in negative energy release for MT102. The suggested fix is to change this line to:
`xx=abs(c(l))`
Credit to the JENDL team for highlighting this fix.

https://github.com/njoy/NJOY2016/blob/1cb7237b89c92eb7a469e3727179cf439835d3ea/src/heatr.f90#L3231

**Comment by whaeck** [comment]
After some verification of the source code, it would seem that this change is sufficient. The current tests do not change - meaning that we do not have a test that deposits photons locally.

I therefore need to test this on a case with discrete photons only and one with both discrete photons and a continuum spectrum. Do you know of cases like this in JENDL-5 (preferably cases that are not too big in file size since I would have to add them to the resources folder)?

**Comment by whaeck** [comment]
A side note about this:

LAW = 1 data in MF6 allows for discrete photons to be specified before the continuum spectrum (this is what ND specifies). For those discrete photon energies, those that represent primary photons are flagged by a negative energy. It would seem that NJOY was not updated to take that into account. When depositing photons locally, it can lead to negative kerma values, especially if no continuum spectrum is present.

**Comment by jchsublet** [comment]
Another side note about this, yet another ENDF-6 rune delicacy..

Giving the gamma distribution of an MT102 in MF6 if allowed (not preferred), present many pitfalls in terms of file 6 flavour (in format; negative discrete primary are indeed permitted), completeness (no recoil given in most JENDL-5) and single interpretation when heating is concerned. Heatr is obliged to use one particule momentum approximation if the MF6 is incomplete, and photon momentum when gamma are locally deposited and not in MF12. They will be read and transported in an Acer file though ,but have a peak at for example the discrete lines and continuum of JENDL-5 Fe056 MF6 mt102 [mt102-Fe056chk.pdf](https://github.com/njoy/NJOY2016/files/10019897/mt102-Fe056chk.pdf)
